# Generated by Django 3.2.16 on 2023-05-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20230220_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_end', models.CharField(max_length=1000, verbose_name='出发—终点')),
                ('time_day', models.CharField(max_length=1000, verbose_name='日期')),
                ('airline', models.CharField(max_length=1000, verbose_name='航空公司')),
                ('vecto', models.CharField(max_length=1000, verbose_name='飞机型号')),
                ('start_location', models.CharField(max_length=1000, verbose_name='出发机场')),
                ('start_time', models.CharField(max_length=1000, verbose_name='出发时间')),
                ('end_time', models.CharField(max_length=1000, verbose_name='到达时间')),
                ('end_location', models.CharField(max_length=1000, verbose_name='到达机场')),
                ('floor_proce', models.IntegerField(verbose_name='票价')),
                ('url', models.CharField(max_length=1000, verbose_name='信息来源')),
            ],
        ),
    ]
