# Generated by Django 4.2.11 on 2024-03-29 08:42
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [
        ('app01', '0008_flightticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightticket',
            old_name='floor_proce',
            new_name='floor_price',
        ),
    ]
